FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["LOCPS.WebApi/LOCPS.WebApi.csproj", "LOCPS.WebApi/"]
COPY ["LOCPS.Shared/LOCPS.Shared.csproj", "LOCPS.Shared/"]
RUN dotnet restore "LOCPS.WebApi/LOCPS.WebApi.csproj"
COPY . .
RUN dotnet build "LOCPS.WebApi/LOCPS.WebApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "LOCPS.WebApi/LOCPS.WebApi.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "LOCPS.WebApi.dll"]
